---
title: "Worksheet#4 in R"
author: "Mark Lexter Sicabalo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Worksheet-4 in R
#Sicabalo, Mark Lexter BSIT 2-A

#1. The table below shows the data about shoe size and height. Create a data frame.
#a. Describe the data.
Shoesize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
Gender <- c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")

shoeclsf <- data.frame(Shoesize,Height,Gender)
shoeclsf
```

```{r}
#b. Find the mean of shoe size and height of the respondents. Copy the codes and results.

summary(shoeclsf)

#Shoesize: Mean   : 9.411
#Height: Mean   :68.57

#c. Is there a relationship between shoe size and height? Why?
#Yes, because the higher the height of the person the bigger the shoesize is.
#The factors levels below the actual values.
```

```{r}
#Factors
#2. Construct character vector months to a factor with factor() and assign the result to
#factor_months_vector. Print out factor_months_vector and assert that R prints out
#the factor levels below the actual values.

Months <- c("March","April","January","November","January",
            "September","October","September","November",
            "August","January","November","November",
            "February","May","August","July","December",
            "August","August","September","November","February","April")

factor_Months <- factor(Months)
factor_Months
```

```{r}
#3. Then check the summary() of the months_vector and factor_months_vector. |
#Interpret the results of both vectors. Are they both equally useful in this case?

summary(Months)

summary(factor_Months)

#Yes, it's because in summary of months it can identify the length, class, and mode of data Months.
#And also in summary of data factor_Months it identify how many months like arpil are in data. 
```

```{r}
#4. Create a vector and factor for the table below.

factor_data <- c(1,4,3)

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

```{r, include=TRUE}
#5. Enter the data below in Excel with file name = import_march.csv

import_march <- read_csv("/cloud/project/cs101_activity/worksheet#4/import_march.csv")
View(import_march)
#a. Import the excel file into the Environment Pane using read.table() function.
#Write the code.

library(readr)
import_march <- read_csv("/cloud/project/cs101_activity/worksheet#4/import_march.csv")
View(import_march)
import_file <- read.table("/cloud/project/cs101_activity/worksheet#4/import_march.csv", header = TRUE, sep = ',')
import_file

#b. View the dataset. Write the code and its result.

View(import_file)
```