---
title: "RWorksheet_Sicabalo#5"
author: "Mark Lexter Sicabalo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Worksheet#5
#Mark lexter Sicabalo BSIT 2-A

#1. The table shows the enrollment of BS in Computer Science, SY 2010-2011.

students <- data.frame("Course Year"= c("1st","2nd","3rd","4th"), "2019-2020" = c(80, 75, 70, 60))
students

#a. Plot the data using a bar graph. Write the codes and copy the result.
stud_dta <- c("1st" = 80, "2nd" = 75, "3rd" = 70, "4th" = 60)
barplot(stud_dta)

#b.Using the same table, label the barchart with Title = ” Enrollment of BS Computer Science horizontal axis = “Curriculum Year” and vertical axis = “number of students”
stud_dta <- c("1st" = 80, "2nd" = 75, "3rd" = 70, "4th" = 60)
barplot(stud_dta, main = "Enrollment of BS Computer Science", xlab = "number of students", ylab = "Course Year")
```

```{r}
#2. The monthly income of De Jesus family was spent on the following: 60% on Food, 10% on electricity, 5% for savings, and 25% for other miscellaneous expenses.

#a. Create a table for the above scenario. Write the codes and its result.

debit <- c("Food","Electricity","Savings","Miscellaneous_expenses")
money <- c(60, 10, 5, 25)

spend <- data.frame(debit, money)
spend

tble <- table(spend)
tble
```

```{r}
#b. Plot the data using a pie chart. Add labels, colors and legend. Write the codes and its result.

money = c(60, 10, 5, 25)

dta <- round(money/sum(money)*100,1)
dta <- paste(dta, "%", sep = " ")

piechrt <- pie(money, labels = dta, cex = 0.8 , col = rainbow(4),main = "De Jesus family Monthly Expense") 
legend ("topright", c("Food", "Electricity", "Savings", "Miscellaneous_expenses"), 
        cex = 0.8 , fill = rainbow(4))
```

```{r}
#3. Open the mtcars dataset.
#a. Create a simple histogram specifically for mpg (miles per gallon) variable.
#Use $ to select the mpg only. Write the codes and its result.

data(mtcars)

mcars <-(mtcars$mpg)
mcars

hist(mtcars$mpg)

#b. Colored histogram with different number of bins. hist(mtcars$mpg, breaks=12, col="red") Note: breaks= controls the number of bins.

hist(mtcars$mpg, breaks=12, col="red")
```

```{r}
#c. Add a Normal Curve
#x <- mtcars$mpg
#h<-hist(x, breaks=10, col="red", xlab="Miles Per Gallon",
#        main="Histogram with Normal Curve")
#xfit<-seq(min(x),max(x),length=40)
#yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
#yfit <- yfit*diff(h$mids[1:2])*length(x)
#lines(xfit, yfit, col="blue", lwd=2)
#Copy the result.

x <- mtcars$mpg
h<-hist(x, breaks=10, col="red", xlab="Miles Per Gallon",
        main="Histogram with Normal Curve")
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=2)
```

```{r}
#4. Open the iris dataset. Create a subset for each species.
#a. Write the codes and its result.

data("iris")

spcies <- data.frame(iris)
spcies

setosaDF <- data.frame(iris)
setosaDF

versicolorDF <- data.frame(iris)
versicolorDF

virginicaDF <- data.frame(iris)
virginicaDF

setosa <- subset(setosaDF, Species == 'setosa')
setosa

versicolor <- subset(versicolorDF, Species == 'versicolor')
versicolor

virginica <- subset(virginicaDF, Species == 'virginica')
virginica
```

```{r}
#b. Get the mean for every characteristics of each species using colMeans().
#Write the codes and its result.
#Example: setosa <- colMeans(setosa[sapply(setosaDF,is.numeric)])

setosa1 <- colMeans(setosa[sapply(setosaDF, is.numeric)])
setosa1

virginica1 <- colMeans(virginica[sapply(virginicaDF, is.numeric)])
virginica1

versicolor1 <- colMeans(versicolor[sapply(versicolorDF, is.numeric)])
versicolor1
```

```{r}
#c. Combine all species by using rbind()
#The table should be look like this:

cmbne <- rbind(setosa1, versicolor1, virginica1)
dfcmbne <- data.frame(cmbne)
dfcmbne

#d. From the data in 4-c: Create the barplot().
#Write the codes and its result.
#The barplot should be like this.

barplot(height = as.matrix(dfcmbne), main = "Iris Data", 
        ylab = "Mean Scores", 
        beside = T, col = rainbow(3))
```
