---
title: "Individual_Project#2"
author: "Mark Lexter Sicabalo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=TRUE}
library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)

#set up the credentials
CONSUMER_KEY <- "TePwgjlqiIoeS7eaAFA6Zx5bC"
CONSUMER_SECRET <- "q8EFgX9LgNV7fLJ053B86r2ZfnFlVYHoImJPpdDpekArQjfc85"
ACCESS_TOKEN <- "1198911894733504513-9S5NveHRcLMeX2T6fQfMbUHdtxPRgF"
ACCESS_SECRET <- "iXC27jpiMT87qXCgWUoMh0Qpcx9V1dcmn0Y8DBPkYhC7z"

setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)


#extracting tweets
tweets1 <- searchTwitter("#JENNIE", n=10000, lang="en", since="2022-12-12", until="2022-12-18", retryOnRateLimit = 120)
tweets1

#converting list to dataframe
trend_tweetsDF <- twListToDF(tweets1)

#saving file
save(trend_tweetsDF,file = "TweetsDF.Rdata")

#load file
load(file = "TweetsDF.Rdata")
```

```{r, include=TRUE}
#checking if she miss me, missing value
sap_data <- sapply(trend_tweetsDF, function(x) sum(is.na(x)))
sap_data

#Tweets
#subsetting using dplyr()
tweets <- trend_tweetsDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)
tweets

#grouped the data 
tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

crt_data <- tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
crt_data

mn <- tweets %>% pull(created) %>% min()
mn 
mx <- tweets %>% pull(created) %>% max()
mx
```

```{r, include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plt_data <- ggplot(crt_data, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")

plt_data %>% ggplotly()

#==============
#Retweets

sub_tweets <- trend_tweetsDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == TRUE)
sub_tweets


sub_tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

crt2 <- sub_tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
crt2

mn <- sub_tweets %>% pull(created) %>% min()
mn 
mx <- sub_tweets %>% pull(created) %>% max()
mx
```

```{r, include=TRUE}
# Plot on tweets by time using the library(plotly) and ggplot().
plt_data <- ggplot(crt2, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "midnightblue", high = "aquamarine4")

plt_data %>% ggplotly()
```
